xdim=256
echo "======================================="
echo "every second core"
echo "======================================="
echo "1 thread"
OMP_NUM_THREADS=1 aprun -cc 0 ./main $xdim $xdim 20 0.005 | grep "simulation took"
echo "2 thread"
OMP_NUM_THREADS=2 aprun -cc 0,2 ./main $xdim $xdim 20 0.005 | grep "simulation took"
echo "3 thread"
OMP_NUM_THREADS=3 aprun -cc 0,2,4 ./main $xdim $xdim 20 0.005 | grep "simulation took"
echo "4 thread"
OMP_NUM_THREADS=4 aprun -cc 0,2,4,8 ./main $xdim $xdim 20 0.005 | grep "simulation took"

echo "======================================="
echo "every core"
echo "======================================="
echo "1 thread"
OMP_NUM_THREADS=1 aprun -cc 0 ./main $xdim $xdim 20 0.005 | grep "simulation took"
echo "2 thread"
OMP_NUM_THREADS=2 aprun -cc 0-1 ./main $xdim $xdim 20 0.005 | grep "simulation took"
echo "3 thread"
OMP_NUM_THREADS=3 aprun -cc 0-2 ./main $xdim $xdim 20 0.005 | grep "simulation took"
echo "4 thread"
OMP_NUM_THREADS=4 aprun -cc 0-3 ./main $xdim $xdim 20 0.005 | grep "simulation took"
echo "8 thread"
OMP_NUM_THREADS=8 aprun -cc 0-7 ./main $xdim $xdim 20 0.005 | grep "simulation took"
